apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: generator

resources:
- Deployment.yml
- Namespace.yml
- Service.yml

secretGenerator:
  - name: generator-secrets
    env: .env
