trigger:
  - master

variables:
  - template: variables.yml

pool: my_mac

steps:

  # - template: docker_login.yml


  - template: build_docker.yml


  # - template: run_docker.yml


  # - template: init_vault.yml


  # - template: deploy_app.yml