trigger:
  - master

variables:
  - template: variables.yml

pool: mac

steps:

  - template: build_docker.yml


  - template: run_docker.yml


  - template: init_vault.yml


  - template: deploy_app.yml